---
- name: OpenAM Configuration Test
  hosts: local
  tasks:
    - name: initial configuration of openam
      ssoconfigure:
        # SERVER_URL is the URL of the web container on which OpenAM 
        # Server is deployed.
        server_url: "http://openam.example.com:8080"

        # DEPLOYMENT_URI is the OpenAM Server deployment URI.
        deployment_uri: "/openam"

        # BASE_DIR is the configuration directory
        base_dir: "/opt/tomcat/openam"

        # locale is the user locale.
        locale: "en_US"

        # PLATFORM_LOCALE is is the locale of OpenAM Server.
        platform_locale: "en_US"

        # AM_ENC_KEY is the password encryption key.  In a multiserver 
        # installation, this parameter must have the same value as the 
        # other servers.  By default, AM_ENC_KEY is set to "" which 
        # means that OpenAM Server will generate a random password 
        # encryption key.
        #
        # E.g. output of the following:
        # date +%s | sha256sum | base64 | head -c 36 ; echo
        am_enc_key: "NzFkMWYxOWUyNGVjMDZhN2I1MjUxZTY3NTM4"

        # ADMIN_PWD is the password for the default user, amAdmin. The 
        # password must be at least 8 characters in length. If this 
        # configuration will be part of an existing deployment, the password 
        # you enter must match that of the original deployment.
        admin_pwd: "password"

        # AMLDAPUSERPASSWD is the password for default policy agent 
        # [UrlAccessAgent]. The password must be at least 8 characters 
        # in length. If this configuration will be part of an existing 
        # deployment, the password you enter must match that of the 
        # original deployment.
        amldapuserpasswd: "password2"

        # COOKIE_DOMAIN is the name of the trusted DNS domain that OpenAM 
        # Server returns to a browser when it grants a session ID to a user.
        cookie_domain: ".securekey.com"

        # ACCEPT_LICENSES is a boolean value. The value true will auto-accept 
        # the license, any other value will result in an error
        acceptlicense: true

        # DATA_STORE is the type of configuration data store. Valid values are
        # 'embedded'  - OpenAM embedded OpenDJ server
        # 'dirServer' - ForgeRock OpenDJ or Oracle Directory Server 
        #               Enterprise Edition
        # If 'dirServer' is specified and the configuration data store contains
        # configuration of existing OpenAM Servers, this OpenAM Server will be
        # added to the existing multi-server setup.
        data_store: "embedded"

        # DIRECTORY_SSL specifies if the configuration data store is using SSL.
        # Valid values are
        # 'SSL' - SSL
        # 'SIMPLE' - none SSL
        directory_ssl: "SIMPLE"

        # DIRECTORY_SERVER is the host name of the configuration data store.
        directory_server: "openam.example.com"

        # DIRECTORY_PORT is the port on which the configuration data store is
        # listening for connections.
        directory_port: 50389

        # DIRECTORY_ADMIN_PORT is the admin port on which the configuration data
        # store listens for administrative functions. This setting is only 
        # required if you are using the embedded OpenDJ, if you are using an 
        # external configuration store you can ignore this property
        directory_admin_port: "4444"

        # DIRECTORY_JMX_PORT is the jmx port on which the configuration data
        # store listens for JMX connections. This setting is only required
        # if you are using the embedded OpenDJ, if you are using an external
        # configuration store you can ignore this property
        directory_jmx_port: "1689"

        # ROOT_SUFFIX is the initial or root suffix of the configuration 
        # data store.
        root_suffix: "dc=openam,dc=forgerock,dc=org"

        # DS_DIRMGRDN is the DN (distinguished name) of the directory manager,
        # the user who has unrestricted access to the configuration data store.
        ds_dirmgrdn: "cn=Directory Manager"

        # DS_DIRMGRPASSWD is the password for the directory manager of the
        # configuration data store.
        ds_dirmgrpasswd: "password"

